# Data Understanding EDA

In [ ]:
# %pip install pandas
%pip install numpy jinja2 matplotlib seaborn

In [4]:
import pandas as pd

# Load dataset
df = pd.read_csv("Car Sales.xlsx - car_data.csv")   # ya Excel ho to read_excel()

# First look
df.head()

# Shape
df.shape

# Columns
df.columns

# Data types
df.info()

# Summary stats
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 23906 entries, 0 to 23905
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   git push origin mainCar_id  23906 non-null  str
 1   Date                        23906 non-null  str
 2   Customer Name               23905 non-null  str
 3   Gender                      23906 non-null  str
 4   Annual Income               23906 non-null  int64
 5   Dealer_Name                 23906 non-null  str
 6   Company                     23906 non-null  str
 7   Model                       23906 non-null  str
 8   Engine                      23906 non-null  str
 9   Transmission                23906 non-null  str
 10  Color                       23906 non-null  str
 11  Price ($)                   23906 non-null  int64
 12  Dealer_No                   23906 non-null  str
 13  Body Style                  23906 non-null  str
 14  Phone                       23906 non-null  int64
 15  Dealer_Region               23906 non-null  str
dtypes: int64(3), str(13)
memory usage: 2.9 MB

       Annual Income     Price ($)         Phone
count   2.390600e+04  23906.000000  2.390600e+04
mean    8.308403e+05  28090.247846  7.497741e+06
std     7.200064e+05  14788.687608  8.674920e+05
min     1.008000e+04   1200.000000  6.000101e+06
25%     3.860000e+05  18001.000000  6.746495e+06
50%     7.350000e+05  23000.000000  7.496198e+06
75%     1.175750e+06  34000.000000  8.248146e+06
max     1.120000e+07  85800.000000  8.999579e+06

## 1. Setup & Imports

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import warnings
warnings.filterwarnings('ignore')

# Plot style
plt.rcParams['figure.facecolor'] = '#F8FAFC'
plt.rcParams['axes.facecolor'] = '#F8FAFC'
plt.rcParams['font.family'] = 'sans-serif'

COLORS = ['#2563EB','#7C3AED','#DB2777','#EA580C','#16A34A','#0891B2','#CA8A04']
ACCENT = '#1E293B'
print("✅ Libraries imported successfully")

✅ Libraries imported successfully

In [8]:
# Data types and memory usage
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23906 entries, 0 to 23905
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   git push origin mainCar_id  23906 non-null  str
 1   Date                        23906 non-null  str
 2   Customer Name               23905 non-null  str
 3   Gender                      23906 non-null  str
 4   Annual Income               23906 non-null  int64
 5   Dealer_Name                 23906 non-null  str
 6   Company                     23906 non-null  str
 7   Model                       23906 non-null  str
 8   Engine                      23906 non-null  str
 9   Transmission                23906 non-null  str
 10  Color                       23906 non-null  str
 11  Price ($)                   23906 non-null  int64
 12  Dealer_No                   23906 non-null  str
 13  Body Style                  23906 non-null  str
 14  Phone                       23906 non-null  int64
 15  Dealer_Region               23906 non-null  str
dtypes: int64(3), str(13)
memory usage: 2.9 MB

In [9]:
# Quick statistical summary
df.describe()

       Annual Income     Price ($)         Phone
count   2.390600e+04  23906.000000  2.390600e+04
mean    8.308403e+05  28090.247846  7.497741e+06
std     7.200064e+05  14788.687608  8.674920e+05
min     1.008000e+04   1200.000000  6.000101e+06
25%     3.860000e+05  18001.000000  6.746495e+06
50%     7.350000e+05  23000.000000  7.496198e+06
75%     1.175750e+06  34000.000000  8.248146e+06
max     1.120000e+07  85800.000000  8.999579e+06

## 3. Data Wrangling

### 3.1 Missing Values

In [10]:
# Check missing values
missing = df.isnull().sum()
print("Missing values per column:")
print(missing[missing > 0] if missing.sum() > 0 else "✅ No missing values found")
print()

# Fill the 1 missing Customer Name
df['Customer Name'].fillna('Unknown', inplace=True)
print(f"After fill — missing in 'Customer Name': {df['Customer Name'].isnull().sum()}")

Missing values per column:
Customer Name    1
dtype: int64

After fill — missing in 'Customer Name': 1

### 3.2 Duplicate Removal

In [11]:
dupes = df.duplicated().sum()
print(f"Duplicate rows found: {dupes}")
df = df.drop_duplicates()
print(f"✅ Dataset shape after dedup: {df.shape}")

Duplicate rows found: 0
✅ Dataset shape after dedup: (23906, 16)

### 3.3 Data Type Corrections

In [12]:
# Convert Date to datetime
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
print("Date dtype:", df['Date'].dtype)

# Fix hidden non-breaking space character in Engine column
df['Engine'] = df['Engine'].str.replace('\xa0', ' ').str.strip()
print("\nUnique engine types after cleaning:")
print(df['Engine'].value_counts())

Date dtype: datetime64[us]

Unique engine types after cleaning:
Engine
DoubleÂ Overhead Camshaft    12571
Overhead Camshaft            11335
Name: count, dtype: int64

### 3.4 Filtering & Transformations

In [14]:
# Verify numeric columns
df['Price ($)'] = pd.to_numeric(df['Price ($)'], errors='coerce')
df['Annual Income'] = pd.to_numeric(df['Annual Income'], errors='coerce')

# Price range check
print(f"Price range: ${df['Price ($)'].min():,.0f} — ${df['Price ($)'].max():,.0f}")
print(f"Income range: ${df['Annual Income'].min():,.0f} — ${df['Annual Income'].max():,.0f}")

# Flag extreme outliers (for reference, not dropped)
outliers = df[df['Annual Income'] > 5_000_000]
print(f"\nHigh income outliers (>$5M): {len(outliers)} records ({len(outliers)/len(df)*100:.2f}% of data)")

Price range: $1,200 — $85,800
Income range: $10,080 — $11,200,000

High income outliers (>$5M): 37 records (0.15% of data)

### 3.5 Summary After Wrangling

In [15]:
print("=" * 50)
print("DATASET SUMMARY AFTER WRANGLING")
print("=" * 50)
print(f"Total Records     : {len(df):,}")
print(f"Total Features    : {df.shape[1]}")
print(f"Missing Values    : {df.isnull().sum().sum()}")
print(f"Duplicate Rows    : {df.duplicated().sum()}")
print(f"Date Range        : {df['Date'].min().date()} → {df['Date'].max().date()}")
print(f"Unique Brands     : {df['Company'].nunique()}")
print(f"Unique Dealers    : {df['Dealer_Name'].nunique()}")
print(f"Regions           : {df['Dealer_Region'].nunique()}")
print(f"Total Revenue     : ${df['Price ($)'].sum():,.0f}")
print("=" * 50)

==================================================
DATASET SUMMARY AFTER WRANGLING
==================================================
Total Records     : 23,906
Total Features    : 16
Missing Values    : 1
Duplicate Rows    : 0
Date Range        : 2022-01-02 → 2023-12-31
Unique Brands     : 30
Unique Dealers    : 28
Regions           : 7
Total Revenue     : $671,525,465
==================================================